/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApartmentsIndexRouteImport } from './routes/apartments.index'
import { Route as ApartmentsSlugRouteImport } from './routes/apartments.$slug'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentsIndexRoute = ApartmentsIndexRouteImport.update({
  id: '/apartments/',
  path: '/apartments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentsSlugRoute = ApartmentsSlugRouteImport.update({
  id: '/apartments/$slug',
  path: '/apartments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/apartments/$slug': typeof ApartmentsSlugRoute
  '/apartments/': typeof ApartmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/apartments/$slug': typeof ApartmentsSlugRoute
  '/apartments': typeof ApartmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/apartments/$slug': typeof ApartmentsSlugRoute
  '/apartments/': typeof ApartmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/services'
    | '/apartments/$slug'
    | '/apartments/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/services' | '/apartments/$slug' | '/apartments'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/services'
    | '/apartments/$slug'
    | '/apartments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  ApartmentsSlugRoute: typeof ApartmentsSlugRoute
  ApartmentsIndexRoute: typeof ApartmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartments/': {
      id: '/apartments/'
      path: '/apartments'
      fullPath: '/apartments/'
      preLoaderRoute: typeof ApartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartments/$slug': {
      id: '/apartments/$slug'
      path: '/apartments/$slug'
      fullPath: '/apartments/$slug'
      preLoaderRoute: typeof ApartmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  ApartmentsSlugRoute: ApartmentsSlugRoute,
  ApartmentsIndexRoute: ApartmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
